[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"

[font]
size = 16

# SpawnNewInstance
[keyboard]
bindings = [
  { key = "Enter", mods = "Control", action = "SpawnNewInstance" },
]

[window]
decorations = "Buttonless"
option_as_alt = "Both"
dynamic_padding = true

[selection]
save_to_clipboard = true
