---
- name: My Thinkpad X1 gen7 laptop provisioning
  hosts: localhost
  become: yes
  vars:
    gen_warning: "WARNING! This file is controlled by Ansible script."
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"
  tasks:
    - name: create and setup aur_builder user
      user: name=aur_builder
    - name: grant aur_builder more permissions
      lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/bin/visudo -cf %s
        create: yes
    - name: create projects dir
      file:
        path: "{{ local_home }}/projects"
        state: directory
        mode: '0755'
    - name: packages
      pacman:
        update_cache: yes
        name:
          - mc
          - zip
          - tree
          - unzip
          - unrar
          - jq
          - xf86-video-intel
          - xorg
          - xorg-xinit
          #- i3
          - xf86-input-libinput
          - chrony
          - py3status
          - dmenu
          - pango
          - ttf-dejavu
          - zenity
          - thunderbird
          - xdg-utils
          - perl-file-mimeinfo
          - dunst
          - go
          - go-tools
          - htop
          - tor
          - fwupd
          - wget
          - pulseaudio
          - blueman
          - pulseaudio-bluetooth
          - ntfs-3g
          - udiskie
          - docker
          - docker-compose
          - docker-machine
          - remmina
          - freerdp
          - virtualbox-host-modules-arch
          - virtualbox
          - virtualbox-guest-iso
          - acpi
          - acpid
          - ttf-opensans
          - xclip
          - tlp
          - tp_smapi
          - acpi_call
          - ethtool
          - efibootmgr
          - iotop
          - picom
          - hsetroot
          - telegram-desktop
          - pavucontrol
          - vlc
          - sof-firmware
          - pinta
          - texlive-most
          - gummi
          - inkscape
          - soundfont-fluid
    - name: AUR packages
      aur:
        name:
          - rxvt-unicode-patched
          - xinit-xsession
          - networkmanager-dispatcher-chrony
          - j4-dmenu-desktop-git
          - pulseaudio-ctl
          - flameshot-git
          - jetbrains-toolbox
          - safeeyes
          - google-chrome
          - watson
          - antibody
          - micro
          - vk-messenger
          - grive
          - xkb-switch
          - virtualbox-ext-oracle
          - vlc-plugin-fluidsynth
        skip_installed: yes
      become: yes
      become_user: aur_builder
    - name: generate Xorg fonts index 100dpi
      command: mkfontdir /usr/share/fonts/100dpi
    - name: Configure display size (automatically detected size is incorrect)
      blockinfile:
        path: "/etc/X11/xorg.conf.d/90-monitor.conf"
        create: yes
        content: |
          Section "Monitor"
            Identifier    "<default monitor>"
            DisplaySize   310 174
          EndSection
    - name: Configure Keyboard layout and toggling
      blockinfile:
        path: "/etc/X11/xorg.conf.d/00-keyboard.conf"
        create: yes
        content: |
          Section "InputClass"
            Identifier "system-keyboard"
            MatchIsKeyboard "on"
            Option "XkbLayout" "us,ru"
            Option "XkbOptions" "grp:caps_toggle,grp_led:caps"
          EndSection
    - name: Configure Volume control buttons
      blockinfile:
        path: "/usr/share/pulseaudio/alsa-mixer/paths/analog-output.conf.common"
        marker: "; {mark} ANSIBLE MANAGED BLOCK"
        insertbefore: \[Element PCM\]
        content: |
          [Element Master]
          switch = mute
          volume = ignore
    - name: Congfigure Backlight control
      blockinfile:
        path: "/etc/X11/xorg.conf.d/10-intel_backlight.conf"
        create: yes
        content: |
          Section "Device"
            Identifier  "card0"
            Driver      "intel"
            Option      "Backlight"  "intel_backlight"
            BusID       "PCI:0:2:0"
          EndSection
    - name: Lock screen automatically on Wake from sleep (suspend)
      blockinfile:
        path: /etc/systemd/system/wakelock.service
        create: yes
        content: |
          [Unit]
          Description=Runs i3lock on system resume from a suspended state
          Before=systemd-suspend.service
          
          [Service]
          User={{ local_user }}
          Type=forking
          Environment=DISPLAY=:0
          ExecStart=/home/{{ local_user }}/scripts/lock-screen.sh
          
          [Install]
          WantedBy=sleep.target
          WantedBy=suspend.target
          
    - name: Enable wakelock service
      systemd:
        enabled: yes
        name: wakelock
    - name: Handy symlink for mounted devices
      file:
        state: link
        force: yes
        owner: "{{ local_user }}"
        dest: "/home/{{ local_user }}/media"
        src: "/run/media/{{ local_user }}"
    - name: Add Mic Mute keyboard event handler (Fn+F4=F20)
      copy:
        content: |
          # {{ gen_warning }}
          event=button/f20 F20 00000080 00000000 K
          action=/etc/acpi/lenovo-mutemic.sh
        dest: /etc/acpi/events/lenovo-mutemic
    - name: Add Mic Mute LED control script
      copy:
        content: |
          #!/bin/bash
          # {{ gen_warning }}
          INPUT_DEVICE="'Capture'"
          LED_BRIGHTNESS="/sys/devices/platform/thinkpad_acpi/leds/platform::micmute/brightness"
          if amixer sget $INPUT_DEVICE,0 | grep '\[on\]' ; then
              if [ "$1" != "update_led_only" ]; then
                  amixer sset $INPUT_DEVICE,0 nocap
              fi
              echo "1" > $LED_BRIGHTNESS
          else
              if [ "$1" != "update_led_only" ]; then
                  amixer sset $INPUT_DEVICE,0 cap
              fi
              echo "0" > $LED_BRIGHTNESS
          fi
        dest: /etc/acpi/lenovo-mutemic.sh
        mode: 0777
    - name: Enable and start acpid service
      systemd:
        enabled: yes
        state: started
        name: acpid
    - name: Add NTP servers to chrony config
      blockinfile:
        path: /etc/chrony.conf
        content: |
          server 0.ru.pool.ntp.org
          server 1.ru.pool.ntp.org
          server 2.ru.pool.ntp.org
          server 3.ru.pool.ntp.org
    - name: Enable and start chronyd service
      systemd:
        enabled: yes
        state: started
        name: chronyd
    - name: Configure TLP
      copy:
        force: yes
        dest: /etc/default/tlp
        src: ./configs/tlp
    - name: Enable and start tlp service
      systemd:
        enabled: yes
        state: started
        name: tlp
    - name: Update zsh plugins
      become: yes
      become_user: "{{ local_user }}"
      command: "{{ local_home }}/scripts/update_zsh_plugins.sh"
    - name: Enable periodic TRIM on SSD devices
      systemd:
        enabled: yes
        state: started
        name: fstrim.timer
    - name: Setup a Login Screen look and feel
      copy:
        dest: /etc/issue
        src: ./configs/issue
        force: yes
    - name: Create Windows partition mount folder
      file:
        path: /mnt/windows
        state: directory
    - name: Add fstab entries
      blockinfile:
        path: /etc/fstab
        content: |
          tmpfs /home/nikita/.cache tmpfs	noatime,nodev,nosuid,size=1024M	0	0
          /dev/nvme0n1p3    /mnt/windows    ntfs    defaults,rw
    - name: Apply fstab updates
      command: mount -a
    - name: Add Windows fonts
      file:
        src: /mnt/windows/Windows/Fonts
        dest: /usr/share/fonts/WindowsFonts
        state: link
    - name: Update Font cache
      command: fc-cache -f
    - name: Add more power-saving options
      blockinfile:
        path: /etc/sysctl.d/powersave.conf
        create: yes
        content: |
          kernel.nmi_watchdog = 0
          vm.dirty_writeback_centisecs = 6000
    - name: Allow users to build Golang sources
      file:
        path: /usr/lib/go/pkg
        recurse: yes
        state: directory
        mode: '1777'
    - name: Add systemd job to sync Google Drive
      blockinfile:
        path: /etc/systemd/system/google-drive-sync.service
        create: yes
        content: |
          [Unit]
          Description=Runs Grive to sync Google Drive folder
          
          [Service]
          User={{ local_user }}
          Type=oneshot
          Environment=HOME=/home/{{ local_user }}
          ExecStart=/home/{{ local_user }}/scripts/grive-sync.sh
    - name: Add systemd timer to run Google Drive Sync
      blockinfile:
        path: /etc/systemd/system/google-drive-sync.timer
        create: yes
        content: |
          [Unit]
          Description=Run Google Drive sync every 15 min
          
          [Timer]
          OnCalendar=*:0/15
          Persistent=true
          
          [Install]
          WantedBy=timers.target
    - name: Enable google sync
      systemd:
        name: google-drive-sync.service
        enabled: yes
    - name: Enable and start google sync timer
      systemd:
        name: google-drive-sync.timer
        state: started
        enabled: yes
    - name: Enable SysRq hotkeys
      sysctl:
        name: kernel.sysrq
        value: '1'
        state: present
    - name: Kernel modules blacklist
      blockinfile:
        path: /etc/modprobe.d/blacklist.comf
        create: yes
        content: |
          blacklist snd_hda_intel
          blacklist snd_soc_skl
    - name: Configure pulseaudio
      blockinfile:
        path: /etc/pulse/default.pa
        content: |
          load-module module-alsa-sink device=hw:0,0 channels=4
          load-module module-alsa-source device=hw:0,7 channels=4
          